import path from 'node:path';import { fileURLToPath } from 'node:url';
import express from 'express';import helmet from 'helmet';import compression from 'compression';import cors from 'cors';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import bcrypt from 'bcryptjs';
import { config,isProduction } from './config.js';import { COOKIE_NAME,clearCookieOptions,cookieOptions,issueToken,requireAdmin } from './auth.js';import { createEnquiry,listEnquiries,updateEnquiry,persistenceMode } from './repository.js';import { enquirySchema,loginSchema,statusSchema,validate } from './validation.js';
export function createApp(){const app=express();app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:isProduction?undefined:false,crossOriginResourcePolicy:{policy:'same-origin'}}));app.use(compression());app.use(cors({origin:config.clientOrigin,credentials:true}));app.use(express.json({limit:'32kb'}));app.use(cookieParser());
 const general=rateLimit({windowMs:15*60*1000,limit:isProduction?200:1000,standardHeaders:'draft-8',legacyHeaders:false});const contact=rateLimit({windowMs:60*60*1000,limit:isProduction?8:100,standardHeaders:'draft-8',legacyHeaders:false,message:{message:'Too many enquiries from this connection. Please try again later.'}});const loginLimit=rateLimit({windowMs:15*60*1000,limit:isProduction?5:100,skipSuccessfulRequests:true,message:{message:'Too many login attempts. Please try again later.'}});app.use('/api',general);
 app.get('/api/health',(_req,res)=>res.json({status:'ok',database:persistenceMode()}));app.post('/api/enquiries',contact,validate(enquirySchema),async(req,res,next)=>{try{const {website,...input}=req.validated;if(website)return res.status(201).json({message:'Enquiry received.'});const item=await createEnquiry(input);res.status(201).json({message:'Enquiry received.',id:item.id})}catch(err){next(err)}});
 app.post('/api/auth/login',loginLimit,validate(loginSchema),async(req,res)=>{const configured=config.adminEmail&&config.adminHash&&!config.adminHash.includes('REPLACE_');if(!configured)return res.status(503).json({message:'Admin login has not been configured.'});const validEmail=req.validated.email===config.adminEmail;const validPassword=await bcrypt.compare(req.validated.password,config.adminHash);if(!validEmail||!validPassword)return res.status(401).json({message:'Invalid email or password.'});res.cookie(COOKIE_NAME,issueToken(),cookieOptions).json({message:'Signed in.'})});app.post('/api/auth/logout',(_req,res)=>{res.clearCookie(COOKIE_NAME,clearCookieOptions);res.json({message:'Signed out.'})});
 app.get('/api/admin/enquiries',requireAdmin,async(req,res,next)=>{try{const allowed=['all','new','in-progress','resolved'];const status=allowed.includes(req.query.status)?req.query.status:'all';const items=await listEnquiries(status);res.json({items,total:items.length,database:persistenceMode()})}catch(err){next(err)}});app.patch('/api/admin/enquiries/:id',requireAdmin,validate(statusSchema),async(req,res,next)=>{try{const item=await updateEnquiry(req.params.id,req.validated.status);if(!item)return res.status(404).json({message:'Enquiry not found.'});res.json({item})}catch(err){next(err)}});
 if(isProduction){const here=path.dirname(fileURLToPath(import.meta.url));const dist=path.resolve(here,'../../client/dist');app.use(express.static(dist,{maxAge:'1y',index:false}));app.get('/{*splat}',(req,res,next)=>req.path.startsWith('/api/')?next():res.sendFile(path.join(dist,'index.html')))}
 app.use('/api/{*splat}',(_req,res)=>res.status(404).json({message:'API route not found.'}));app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({message:'An unexpected server error occurred.'})});return app}
